- name: PostgreSQL | Setup database
  sudo_user: postgres
  postgresql_db:
    db: "{{ item }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present
    owner: "{{ postgresql_db_user }}"
  with_items: postgresql_databases
  when: postgresql_databases is defined
