- name: PostgresQL | Ensure packages are installed
  action: apt name={{ item }}
  with_items:
    - libpq-dev
    - python-psycopg2

- name: PostgresQL | Install python-pycurl
  apt: pkg=python-pycurl state=latest

- name: PostgresQL | Add repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: PostgresQL | Add repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

- name: PostgresQL | Install
  apt: pkg="postgresql-{{ postgresql_version }}" state=latest update_cache=true

- name: PostgresQL | Install contrib
  apt: pkg=postgresql-contrib-{{ postgresql_version }} state=latest