- name: PostgreSQL | Copy valid pg_hba.conf
  template: src={{ postgresql_hba }} dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf

- name: PostgreSQL | Copy valid postgresql.conf
  template: src={{ postgresql_config }} dest=/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf

- name: PostgreSQL | Restart
  command: service postgresql restart

- name: PostgreSQL | Ensure database is created
  postgresql_user: name={{ postgresql_db_user }} password={{ postgresql_db_user_pass }} encrypted=no role_attr_flags=CREATEDB,NOSUPERUSER
  sudo: yes
  sudo_user: postgres
  register: db_created
  when: postgresql_db_user is defined
  notify:
    - Restart PostgreSQL
