- name: PostgreSQL | Setup database
  sudo_user: postgres
  postgresql_db:
    db: "{{ item }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present
  with_items: postgresql_databases
  when: postgresql_databases is defined

- name: PostgreSQL | Install hstore ext
  sudo_user: postgres
  shell: psql {{ item }} -c "CREATE EXTENSION IF NOT EXISTS hstore;"
  with_items: ppostgresql_databases
  when: postgresql_hstore and postgresql_databases is defined
